// Generated by bridge codegen
export const service = "hello";

export function createClient(baseUrl: string) {
  return {
    async ping(body?: unknown) {
      const response = await fetch(`${baseUrl}/ping`, { method: "GET", headers: { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
      if (!response.ok) throw new Error(`request failed: ${response.status}`);
      return response.text();
    },
    async echo(body?: unknown) {
      const response = await fetch(`${baseUrl}/echo`, { method: "POST", headers: { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
      if (!response.ok) throw new Error(`request failed: ${response.status}`);
      return response.text();
    },
  };
}
