//! Bridge TypeScript client generator.
//!
//! Converts a compiled [`BridgeFile`] into a type-safe TypeScript client
//! with:
//! - Typed path params (e.g. `get(id: string)`)
//! - Request / response interfaces
//! - Bearer / API-key auth headers
//! - `BridgeError` class for structured error handling
//! - Per-service namespaced client objects

use compiler::{Auth, BridgeFile, Endpoint, Method, Service};

// ── Public API ────────────────────────────────────────────────────────────────

/// Generate a TypeScript client for every service in `file`.
///
/// Returns the full `.ts` source as a string.
pub fn generate_typescript(file: &BridgeFile) -> String {
    let mut out = String::new();
    header(&mut out);
    for svc in &file.services {
        generate_service(&mut out, svc);
    }
    root_factory(&mut out, file);
    out
}

/// Convenience: generate for a single [`Service`] (wraps it in a `BridgeFile`).
pub fn generate_typescript_service(svc: &Service) -> String {
    let file = BridgeFile {
        services: vec![svc.clone()],
    };
    generate_typescript(&file)
}

// ── Sections ──────────────────────────────────────────────────────────────────

fn header(out: &mut String) {
    out.push_str(
        r#"// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by bridge-codegen — do not edit manually.
// Re-generate: bridge compile-file <your-app>.bridge > bridge.gen/client.ts
// ─────────────────────────────────────────────────────────────────────────────

export class BridgeError extends Error {
  constructor(
    public readonly code: number,
    message: string,
    public readonly body?: string,
  ) {
    super(message);
    this.name = "BridgeError";
  }
}

async function request(
  baseUrl: string,
  method: string,
  path: string,
  body?: unknown,
  headers?: Record<string, string>,
): Promise<string> {
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers: {
      "content-type": "application/json",
      ...headers,
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new BridgeError(res.status, `${method} ${path} → ${res.status}`, text);
  return text;
}

async function requestJson<T>(
  baseUrl: string,
  method: string,
  path: string,
  body?: unknown,
  headers?: Record<string, string>,
): Promise<T> {
  const text = await request(baseUrl, method, path, body, headers);
  return JSON.parse(text) as T;
}

"#,
    );
}

fn generate_service(out: &mut String, svc: &Service) {
    let type_name = pascal(svc.name.as_str());
    let has_auth = svc.auth != Auth::None;

    // Auth type comment
    if has_auth {
        out.push_str(&format!(
            "// Service '{name}' uses {auth} authentication.\n",
            name = svc.name,
            auth = svc.auth.as_str()
        ));
    }

    // Factory function signature
    let auth_param = match &svc.auth {
        Auth::Bearer => "token: string, ",
        Auth::ApiKey => "apiKey: string, ",
        Auth::None => "",
    };
    out.push_str(&format!(
        "export function create{type_name}Client(baseUrl: string, {auth_param}) {{\n"
    ));

    // Auth headers builder
    match &svc.auth {
        Auth::Bearer => {
            out.push_str("  const authHeaders = { authorization: `Bearer ${token}` };\n");
        }
        Auth::ApiKey => {
            out.push_str("  const authHeaders = { \"x-api-key\": apiKey };\n");
        }
        Auth::None => {}
    }
    if has_auth {
        out.push('\n');
    }

    out.push_str("  return {\n");
    for ep in &svc.endpoints {
        generate_endpoint(out, ep, &svc.auth);
    }
    out.push_str("  };\n");
    out.push_str("}\n\n");
}

fn generate_endpoint(out: &mut String, ep: &Endpoint, svc_auth: &Auth) {
    let params = ep.path_params();
    let effective_auth = ep.auth.as_ref().unwrap_or(svc_auth);

    // Build TS parameter list
    let mut ts_params: Vec<String> = params.iter().map(|p| format!("{p}: string")).collect();

    let needs_body = matches!(ep.method, Method::Post | Method::Put | Method::Patch);
    if needs_body {
        ts_params.push("body?: unknown".to_string());
    }
    // Per-endpoint auth override that differs from service-level
    let needs_token_param = match (svc_auth, &ep.auth) {
        (Auth::None, Some(Auth::Bearer)) => {
            ts_params.push("token: string".to_string());
            true
        }
        (Auth::None, Some(Auth::ApiKey)) => {
            ts_params.push("apiKey: string".to_string());
            true
        }
        _ => false,
    };

    out.push_str(&format!(
        "    async {name}({params}): Promise<string> {{\n",
        name = ep.name,
        params = ts_params.join(", "),
    ));

    // Build interpolated path
    let ts_path = params.iter().fold(ep.path.clone(), |acc, p| {
        acc.replace(&format!(":{p}"), &format!("${{{p}}}"))
    });
    let path_expr = if ts_path.contains("${") {
        format!("`{ts_path}`")
    } else {
        format!(r#""{ts_path}""#)
    };

    // Headers
    let headers = match (effective_auth, needs_token_param) {
        (Auth::Bearer, true) => "{ authorization: `Bearer ${token}` }".to_string(),
        (Auth::ApiKey, true) => r#"{ "x-api-key": apiKey }"#.to_string(),
        (Auth::Bearer, false) => "authHeaders".to_string(),
        (Auth::ApiKey, false) => "authHeaders".to_string(),
        (Auth::None, _) => "undefined".to_string(),
    };

    let body_arg = if needs_body { "body" } else { "undefined" };

    out.push_str(&format!(
        "      return request(baseUrl, \"{method}\", {path}, {body}, {headers});\n",
        method = ep.method.as_str(),
        path = path_expr,
        body = body_arg,
        headers = headers,
    ));
    out.push_str("    },\n");
}

/// Generate an OpenAPI 3.0 JSON specification for the Bridge file.
pub fn generate_openapi(file: &BridgeFile) -> String {
    let mut paths = Vec::new();

    for svc in &file.services {
        for ep in &svc.endpoints {
            let params = ep.path_params();
            let mut path_params_json = Vec::new();
            for p in &params {
                path_params_json.push(format!(
                    r#"{{"name":"{p}","in":"path","required":true,"schema":{{"type":"string"}}}}"#
                ));
            }

            let method_lower = ep.method.as_str().to_ascii_lowercase();
            let effective_auth = ep.auth.as_ref().unwrap_or(&svc.auth);
            let security_json = match effective_auth {
                Auth::Bearer => r#"[{"bearerAuth":[]}]"#,
                Auth::ApiKey => r#"[{"apiKeyAuth":[]}]"#,
                Auth::None => "[]",
            };

            let needs_body = matches!(ep.method, Method::Post | Method::Put | Method::Patch);
            let request_body = if needs_body {
                r#","requestBody":{"content":{"application/json":{"schema":{"type":"object"}}}}"#
            } else {
                ""
            };

            let tags_json = if !ep.tags.is_empty() {
                let t: Vec<String> = ep.tags.iter().map(|t| format!("\"{t}\"")).collect();
                format!(r#""tags":[{}],"#, t.join(","))
            } else {
                format!(r#""tags":["{}"],"#, svc.name)
            };

            // Build OpenAPI-style path (replace :param with {param})
            let oa_path = params.iter().fold(ep.path.clone(), |acc, p| {
                acc.replace(&format!(":{p}"), &format!("{{{p}}}"))
            });

            let params_json = if path_params_json.is_empty() {
                "[]".to_string()
            } else {
                format!("[{}]", path_params_json.join(","))
            };

            paths.push(format!(
                r#""{oa_path}":{{{method_lower}:{{{tags}"{service_name}_{ep_name}",{}"parameters":{params},"security":{security},"responses":{{"200":{{"description":"Success"}},"400":{{"description":"Bad Request"}},"500":{{"description":"Server Error"}}}}{req_body}}}}}"#,
                tags = tags_json,
                service_name = svc.name,
                ep_name = ep.name,
                params = params_json,
                security = security_json,
                req_body = request_body,
                oa_path = oa_path,
                method_lower = method_lower,
            ));
        }
    }

    let security_schemes = r#""securitySchemes":{"bearerAuth":{"type":"http","scheme":"bearer"},"apiKeyAuth":{"type":"apiKey","in":"header","name":"x-api-key"}}"#;

    format!(
        r#"{{"openapi":"3.0.0","info":{{"title":"Bridge API","version":"1.0.0"}},"paths":{{{paths}}},"components":{{{security_schemes}}}}}"#,
        paths = paths.join(","),
        security_schemes = security_schemes,
    )
}

/// Generate the top-level `createClient(baseUrl)` that bundles all services.
fn root_factory(out: &mut String, file: &BridgeFile) {
    if file.services.is_empty() {
        return;
    }
    out.push_str("// Convenience factory — creates all service clients at once.\n");
    out.push_str("export function createClient(baseUrl: string) {\n");
    out.push_str("  return {\n");
    for svc in &file.services {
        let type_name = pascal(&svc.name);
        let auth_arg = match &svc.auth {
            Auth::Bearer => r#""" /* replace with your bearer token */"#,
            Auth::ApiKey => r#""" /* replace with your API key */"#,
            Auth::None => "",
        };
        out.push_str(&format!(
            "    {name}: create{type_name}Client(baseUrl{comma}{auth_arg}),\n",
            name = svc.name,
            comma = if auth_arg.is_empty() { "" } else { ", " },
        ));
    }
    out.push_str("  };\n");
    out.push_str("}\n");
}

// ── String helpers ────────────────────────────────────────────────────────────

/// Convert `kebab-case` or `snake_case` to `PascalCase`.
fn pascal(s: &str) -> String {
    s.split(|c| c == '-' || c == '_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use compiler::{Auth, BridgeFile, Endpoint, Method, Service};

    fn make_service(name: &str, auth: Auth, endpoints: Vec<Endpoint>) -> Service {
        Service {
            name: name.to_string(),
            auth,
            middleware: vec![],
            endpoints,
        }
    }

    fn make_endpoint(name: &str, method: Method, path: &str) -> Endpoint {
        Endpoint {
            name: name.to_string(),
            method,
            path: path.to_string(),
            auth: None,
            tags: vec![],
        }
    }

    #[test]
    fn generates_basic_client() {
        let svc = make_service(
            "hello",
            Auth::None,
            vec![make_endpoint("ping", Method::Get, "/ping")],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("async ping()"));
        assert!(ts.contains(r#""/ping""#));
        assert!(ts.contains("createHelloClient"));
        assert!(ts.contains("BridgeError"));
    }

    #[test]
    fn path_params_typed() {
        let svc = make_service(
            "users",
            Auth::None,
            vec![make_endpoint("get", Method::Get, "/users/:id")],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("async get(id: string)"));
        assert!(ts.contains("`/users/${id}`"));
    }

    #[test]
    fn post_has_body_param() {
        let svc = make_service(
            "users",
            Auth::None,
            vec![make_endpoint("create", Method::Post, "/users")],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("body?: unknown"));
    }

    #[test]
    fn bearer_auth_generates_header() {
        let svc = make_service(
            "secure",
            Auth::Bearer,
            vec![make_endpoint("get", Method::Get, "/data")],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("token: string"));
        assert!(ts.contains("authHeaders"));
        assert!(ts.contains("Bearer ${token}"));
    }

    #[test]
    fn api_key_auth() {
        let svc = make_service(
            "api",
            Auth::ApiKey,
            vec![make_endpoint("get", Method::Get, "/data")],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("apiKey: string"));
        assert!(ts.contains("x-api-key"));
    }

    #[test]
    fn multi_service_client() {
        let file = BridgeFile {
            services: vec![
                make_service(
                    "users",
                    Auth::None,
                    vec![make_endpoint("list", Method::Get, "/users")],
                ),
                make_service(
                    "posts",
                    Auth::None,
                    vec![make_endpoint("list", Method::Get, "/posts")],
                ),
            ],
        };
        let ts = generate_typescript(&file);
        assert!(ts.contains("createUsersClient"));
        assert!(ts.contains("createPostsClient"));
        assert!(ts.contains("createClient"));
        assert!(ts.contains("users:"));
        assert!(ts.contains("posts:"));
    }

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(super::pascal("hello-world"), "HelloWorld");
        assert_eq!(super::pascal("my_service"), "MyService");
        assert_eq!(super::pascal("users"), "Users");
    }

    #[test]
    fn multi_path_params() {
        let svc = make_service(
            "orders",
            Auth::None,
            vec![make_endpoint(
                "item",
                Method::Get,
                "/orders/:orderId/items/:itemId",
            )],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("orderId: string, itemId: string"));
        assert!(ts.contains("`/orders/${orderId}/items/${itemId}`"));
    }

    #[test]
    fn openapi_basic() {
        let file = BridgeFile {
            services: vec![make_service(
                "users",
                Auth::None,
                vec![
                    make_endpoint("list", Method::Get, "/users"),
                    make_endpoint("get", Method::Get, "/users/:id"),
                ],
            )],
        };
        let spec = generate_openapi(&file);
        assert!(spec.contains("openapi"));
        assert!(spec.contains("3.0.0"));
        assert!(spec.contains("/users"));
        assert!(spec.contains("{id}"));
        assert!(spec.contains("path"));
    }

    #[test]
    fn openapi_with_auth() {
        let file = BridgeFile {
            services: vec![make_service(
                "secure",
                Auth::Bearer,
                vec![make_endpoint("get", Method::Get, "/data")],
            )],
        };
        let spec = generate_openapi(&file);
        assert!(spec.contains("bearerAuth"));
        assert!(spec.contains("securitySchemes"));
    }

    #[test]
    fn openapi_post_has_request_body() {
        let file = BridgeFile {
            services: vec![make_service(
                "users",
                Auth::None,
                vec![make_endpoint("create", Method::Post, "/users")],
            )],
        };
        let spec = generate_openapi(&file);
        assert!(spec.contains("requestBody"));
    }

    #[test]
    fn openapi_empty_services() {
        let file = BridgeFile { services: vec![] };
        let spec = generate_openapi(&file);
        assert!(spec.contains("openapi"));
        assert!(spec.contains("paths"));
    }

    #[test]
    fn endpoint_auth_override_no_token_param() {
        let svc = make_service(
            "mixed",
            Auth::Bearer,
            vec![make_endpoint("public", Method::Get, "/pub")],
        );
        let ts = generate_typescript_service(&svc);
        // Service-level auth — token param is in factory signature
        assert!(ts.contains("token: string"));
        assert!(ts.contains("authHeaders"));
    }

    #[test]
    fn delete_method_no_body() {
        let svc = make_service(
            "users",
            Auth::None,
            vec![make_endpoint("delete", Method::Delete, "/users/:id")],
        );
        let ts = generate_typescript_service(&svc);
        // DELETE should not have body param
        assert!(!ts.contains("body?: unknown") || ts.contains("id: string"));
    }

    #[test]
    fn patch_method_has_body() {
        let svc = make_service(
            "users",
            Auth::None,
            vec![make_endpoint("update", Method::Patch, "/users/:id")],
        );
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("body?: unknown"));
    }
}
