use compiler::Service;

pub fn generate_typescript(service: &Service) -> String {
    let mut out = String::new();
    out.push_str("// Generated by bridge codegen\n");
    out.push_str(&format!("export const service = \"{}\";\n\n", service.name));
    out.push_str("export function createClient(baseUrl: string) {\n");
    out.push_str("  return {\n");

    for endpoint in &service.endpoints {
        out.push_str(&format!("    async {}(body?: unknown) {{\n", endpoint.name));
        out.push_str(&format!(
            "      const response = await fetch(`${{baseUrl}}{}`, {{ method: \"{}\", headers: {{ \"content-type\": \"application/json\" }}, body: body === undefined ? undefined : JSON.stringify(body) }});\n",
            endpoint.path, endpoint.method
        ));
        out.push_str(
            "      if (!response.ok) throw new Error(`request failed: ${response.status}`);\n",
        );
        out.push_str("      return response.text();\n");
        out.push_str("    },\n");
    }

    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::generate_typescript;
    use compiler::{Endpoint, Service};

    #[test]
    fn generated_client_contains_endpoint() {
        let service = Service {
            name: "hello".to_string(),
            endpoints: vec![Endpoint {
                name: "ping".to_string(),
                method: "GET".to_string(),
                path: "/ping".to_string(),
            }],
        };
        let generated = generate_typescript(&service);
        assert!(generated.contains("async ping"));
        assert!(generated.contains("/ping"));
    }
}
