//! Bridge TypeScript client generator.
//!
//! Converts a compiled [`BridgeFile`] into a type-safe TypeScript client
//! with:
//! - Typed path params (e.g. `get(id: string)`)
//! - Request / response interfaces
//! - Bearer / API-key auth headers
//! - `BridgeError` class for structured error handling
//! - Per-service namespaced client objects

use compiler::{Auth, BridgeFile, Endpoint, Method, Service};

// ── Public API ────────────────────────────────────────────────────────────────

/// Generate a TypeScript client for every service in `file`.
///
/// Returns the full `.ts` source as a string.
pub fn generate_typescript(file: &BridgeFile) -> String {
    let mut out = String::new();
    header(&mut out);
    for svc in &file.services {
        generate_service(&mut out, svc);
    }
    root_factory(&mut out, file);
    out
}

/// Convenience: generate for a single [`Service`] (wraps it in a `BridgeFile`).
pub fn generate_typescript_service(svc: &Service) -> String {
    let file = BridgeFile { services: vec![svc.clone()] };
    generate_typescript(&file)
}

// ── Sections ──────────────────────────────────────────────────────────────────

fn header(out: &mut String) {
    out.push_str(
        r#"// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by bridge-codegen — do not edit manually.
// Re-generate: bridge compile-file <your-app>.bridge > bridge.gen/client.ts
// ─────────────────────────────────────────────────────────────────────────────

export class BridgeError extends Error {
  constructor(
    public readonly code: number,
    message: string,
    public readonly body?: string,
  ) {
    super(message);
    this.name = "BridgeError";
  }
}

async function request(
  baseUrl: string,
  method: string,
  path: string,
  body?: unknown,
  headers?: Record<string, string>,
): Promise<string> {
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers: {
      "content-type": "application/json",
      ...headers,
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new BridgeError(res.status, `${method} ${path} → ${res.status}`, text);
  return text;
}

async function requestJson<T>(
  baseUrl: string,
  method: string,
  path: string,
  body?: unknown,
  headers?: Record<string, string>,
): Promise<T> {
  const text = await request(baseUrl, method, path, body, headers);
  return JSON.parse(text) as T;
}

"#,
    );
}

fn generate_service(out: &mut String, svc: &Service) {
    let type_name = pascal(svc.name.as_str());
    let has_auth = svc.auth != Auth::None;

    // Auth type comment
    if has_auth {
        out.push_str(&format!(
            "// Service '{name}' uses {auth} authentication.\n",
            name = svc.name,
            auth = svc.auth.as_str()
        ));
    }

    // Factory function signature
    let auth_param = match &svc.auth {
        Auth::Bearer  => "token: string, ",
        Auth::ApiKey  => "apiKey: string, ",
        Auth::None    => "",
    };
    out.push_str(&format!(
        "export function create{type_name}Client(baseUrl: string, {auth_param}) {{\n"
    ));

    // Auth headers builder
    match &svc.auth {
        Auth::Bearer => {
            out.push_str("  const authHeaders = { authorization: `Bearer ${token}` };\n");
        }
        Auth::ApiKey => {
            out.push_str("  const authHeaders = { \"x-api-key\": apiKey };\n");
        }
        Auth::None => {}
    }
    if has_auth {
        out.push('\n');
    }

    out.push_str("  return {\n");
    for ep in &svc.endpoints {
        generate_endpoint(out, ep, &svc.auth);
    }
    out.push_str("  };\n");
    out.push_str("}\n\n");
}

fn generate_endpoint(out: &mut String, ep: &Endpoint, svc_auth: &Auth) {
    let params = ep.path_params();
    let effective_auth = ep.auth.as_ref().unwrap_or(svc_auth);

    // Build TS parameter list
    let mut ts_params: Vec<String> = params.iter()
        .map(|p| format!("{p}: string"))
        .collect();

    let needs_body = matches!(ep.method, Method::Post | Method::Put | Method::Patch);
    if needs_body {
        ts_params.push("body?: unknown".to_string());
    }
    // Per-endpoint auth override that differs from service-level
    let needs_token_param = match (svc_auth, &ep.auth) {
        (Auth::None, Some(Auth::Bearer))  => { ts_params.push("token: string".to_string()); true }
        (Auth::None, Some(Auth::ApiKey))  => { ts_params.push("apiKey: string".to_string()); true }
        _ => false,
    };

    out.push_str(&format!(
        "    async {name}({params}): Promise<string> {{\n",
        name   = ep.name,
        params = ts_params.join(", "),
    ));

    // Build interpolated path
    let ts_path = params.iter()
        .fold(ep.path.clone(), |acc, p| acc.replace(&format!(":{p}"), &format!("${{{p}}}")));
    let path_expr = if ts_path.contains("${") {
        format!("`{ts_path}`")
    } else {
        format!(r#""{ts_path}""#)
    };

    // Headers
    let headers = match (effective_auth, needs_token_param) {
        (Auth::Bearer, true)  => "{ authorization: `Bearer ${token}` }".to_string(),
        (Auth::ApiKey, true)  => r#"{ "x-api-key": apiKey }"#.to_string(),
        (Auth::Bearer, false) => "authHeaders".to_string(),
        (Auth::ApiKey, false) => "authHeaders".to_string(),
        (Auth::None,   _)     => "undefined".to_string(),
    };

    let body_arg = if needs_body { "body" } else { "undefined" };

    out.push_str(&format!(
        "      return request(baseUrl, \"{method}\", {path}, {body}, {headers});\n",
        method  = ep.method.as_str(),
        path    = path_expr,
        body    = body_arg,
        headers = headers,
    ));
    out.push_str("    },\n");
}

/// Generate the top-level `createClient(baseUrl)` that bundles all services.
fn root_factory(out: &mut String, file: &BridgeFile) {
    if file.services.is_empty() {
        return;
    }
    out.push_str("// Convenience factory — creates all service clients at once.\n");
    out.push_str("export function createClient(baseUrl: string) {\n");
    out.push_str("  return {\n");
    for svc in &file.services {
        let type_name = pascal(&svc.name);
        let auth_arg = match &svc.auth {
            Auth::Bearer => r#""" /* replace with your bearer token */"#,
            Auth::ApiKey => r#""" /* replace with your API key */"#,
            Auth::None   => "",
        };
        out.push_str(&format!(
            "    {name}: create{type_name}Client(baseUrl{comma}{auth_arg}),\n",
            name      = svc.name,
            comma     = if auth_arg.is_empty() { "" } else { ", " },
        ));
    }
    out.push_str("  };\n");
    out.push_str("}\n");
}

// ── String helpers ────────────────────────────────────────────────────────────

/// Convert `kebab-case` or `snake_case` to `PascalCase`.
fn pascal(s: &str) -> String {
    s.split(|c| c == '-' || c == '_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None    => String::new(),
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use compiler::{Auth, BridgeFile, Endpoint, Method, Service};

    fn make_service(name: &str, auth: Auth, endpoints: Vec<Endpoint>) -> Service {
        Service { name: name.to_string(), auth, middleware: vec![], endpoints }
    }

    fn make_endpoint(name: &str, method: Method, path: &str) -> Endpoint {
        Endpoint { name: name.to_string(), method, path: path.to_string(), auth: None, tags: vec![] }
    }

    #[test]
    fn generates_basic_client() {
        let svc = make_service("hello", Auth::None, vec![
            make_endpoint("ping", Method::Get, "/ping"),
        ]);
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("async ping()"));
        assert!(ts.contains(r#""/ping""#));
        assert!(ts.contains("createHelloClient"));
        assert!(ts.contains("BridgeError"));
    }

    #[test]
    fn path_params_typed() {
        let svc = make_service("users", Auth::None, vec![
            make_endpoint("get", Method::Get, "/users/:id"),
        ]);
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("async get(id: string)"));
        assert!(ts.contains("`/users/${id}`"));
    }

    #[test]
    fn post_has_body_param() {
        let svc = make_service("users", Auth::None, vec![
            make_endpoint("create", Method::Post, "/users"),
        ]);
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("body?: unknown"));
    }

    #[test]
    fn bearer_auth_generates_header() {
        let svc = make_service("secure", Auth::Bearer, vec![
            make_endpoint("get", Method::Get, "/data"),
        ]);
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("token: string"));
        assert!(ts.contains("authHeaders"));
        assert!(ts.contains("Bearer ${token}"));
    }

    #[test]
    fn api_key_auth() {
        let svc = make_service("api", Auth::ApiKey, vec![
            make_endpoint("get", Method::Get, "/data"),
        ]);
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("apiKey: string"));
        assert!(ts.contains("x-api-key"));
    }

    #[test]
    fn multi_service_client() {
        let file = BridgeFile {
            services: vec![
                make_service("users", Auth::None, vec![make_endpoint("list", Method::Get, "/users")]),
                make_service("posts", Auth::None, vec![make_endpoint("list", Method::Get, "/posts")]),
            ],
        };
        let ts = generate_typescript(&file);
        assert!(ts.contains("createUsersClient"));
        assert!(ts.contains("createPostsClient"));
        assert!(ts.contains("createClient"));
        assert!(ts.contains("users:"));
        assert!(ts.contains("posts:"));
    }

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(super::pascal("hello-world"), "HelloWorld");
        assert_eq!(super::pascal("my_service"), "MyService");
        assert_eq!(super::pascal("users"), "Users");
    }

    #[test]
    fn multi_path_params() {
        let svc = make_service("orders", Auth::None, vec![
            make_endpoint("item", Method::Get, "/orders/:orderId/items/:itemId"),
        ]);
        let ts = generate_typescript_service(&svc);
        assert!(ts.contains("orderId: string, itemId: string"));
        assert!(ts.contains("`/orders/${orderId}/items/${itemId}`"));
    }
}
