[package]
name        = "daemon"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
description = "Bridge daemon: TCP + HTTP server, state management, Docker Postgres orchestration"

[dependencies]
protocol  = { path = "../protocol" }
compiler  = { path = "../compiler" }
codegen   = { path = "../codegen" }
db        = { path = "../db" }
miniredis = { path = "../miniredis" }
