// Generated by bridge codegen
export function createClient(baseUrl: string) {
  return {
    async health() {
      const response = await fetch(`${baseUrl}/health`);
      if (!response.ok) throw new Error(`request failed: ${response.status}`);
      return response.text();
    },
    async modeGet() {
      const response = await fetch(`${baseUrl}/mode`);
      if (!response.ok) throw new Error(`request failed: ${response.status}`);
      return response.text();
    },
    async modeSet(mode: string) {
      const response = await fetch(`${baseUrl}/mode`, { method: "POST", body: mode });
      if (!response.ok) throw new Error(`request failed: ${response.status}`);
      return response.text();
    },
    async compile(source: string) {
      const response = await fetch(`${baseUrl}/compile`, { method: "POST", body: source });
      if (!response.ok) throw new Error(await response.text());
      return response.text();
    },
    async latest() {
      const response = await fetch(`${baseUrl}/db/latest`);
      if (!response.ok) throw new Error(await response.text());
      return response.text();
    },
  };
}
